# Generated by Django 2.2.7 on 2019-12-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedbaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_earn', models.IntegerField()),
                ('profession', models.CharField(max_length=400)),
                ('vested_money_to_withdrow', models.IntegerField()),
                ('feedback_avg_rate', models.IntegerField()),
                ('num_of_feedbacks_he_gave', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=400)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=80)),
                ('gender', models.CharField(max_length=1)),
                ('feedbacker', models.BooleanField()),
                ('isCreator', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('link_to_review_page', models.URLField(default='there is no link')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Creator')),
            ],
        ),
        migrations.CreateModel(
            name='GivenFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='rate by creator')),
                ('is_favorite', models.BooleanField(default=False)),
                ('feedbacker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Feedbaker')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='feedbaker',
            name='feedbacker_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Person'),
        ),
        migrations.AddField(
            model_name='creator',
            name='Creators_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Person'),
        ),
    ]
